version: "3.8"
services:
  playwright-test:
    image: playwright-test
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run usePageObject-chrome
    volumes:
      # copy the test results and playwright report to the host machine
      - ./playwright-report/:/app/playwright-report
      - ./test-results/:/app/test-results
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
